L_Advisory/Controllers/KalendersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using L_Advisory;
using System.Text;

namespace L_Advisory
{
    public partial class Kalender
    {
        // tänane kuupäev
        public int TänaneKp { get { return DateTime.Now.Day; } }

        // päevade arv antud kuus
        public int PäevadeArvKuus { get => DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month); }

    }
}

namespace L_Advisory.Controllers
{

    public class KalendersController : Controller
    {
        public ActionResult BroneeringComplete()
        {
            return View();
        }

        public ActionResult Kalender(int? id)
        {
            DateTime Täna = DateTime.Now.Date.AddDays(id ?? 0);
            DateTime AlgKp = Täna.AddDays(1 - Täna.Day);
            DateTime AlgRida = AlgKp.AddDays(0 - (int)(AlgKp.DayOfWeek));
            ViewBag.Täna = Täna;
            ViewBag.AlgKp = AlgKp;
            ViewBag.AlgRida = AlgRida;
            ViewBag.KalenderId = id ?? 0;

            return View(db.Kalender.ToLookup(x => x.Kuupäev).ToDictionary(x => x.Key, x => x.ToList()));
        }

        private L_AdvisoryEntities db = new L_AdvisoryEntities();

        // GET: Kalenders
        public ActionResult Index()
        {
            var kalender = db.Kalender.Include(k => k.KasutajaUus);
            return View(kalender.ToList());
        }

        // GET: Kalenders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kalender kalender = db.Kalender.Find(id);
            if (kalender == null)
            {
                return HttpNotFound();
            }
            return View(kalender);
        }

        // GET: Kalenders/Create
        public ActionResult Create(int? id)
        {
            int MinaKey = id.Value % 10000;
            int spetsialistKey = id.Value / 10000;
            int Staatus = 1;

            Kalender kalender = new Kalender
            {
                Key = spetsialistKey,
                Kuupäev = DateTime.Now.Date
            };

            ViewBag.St1 = Staatus;
            ViewBag.MinaKey = MinaKey;
            ViewBag.Key = new SelectList(db.KasutajaUus, "Id", "FullName", kalender.Key);
            return View(kalender);
        }

        // POST: Kalenders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]        
        public ActionResult Create([Bind(Include = "nr,Key,Kuupäev,Tund,TunniHInd,Staatus")] Kalender kalender)
        {
            if (ModelState.IsValid)
            {
                db.Kalender.Add(kalender);
                db.SaveChanges(); // siin tekib kalendrile key (nr)
                return RedirectToAction($"Details/{kalender.Key}", "KasutajaUus");
            }

            ViewBag.Key = new SelectList(db.KasutajaUus, "Id", "Eesnimi", kalender.Key);
            return View(kalender);
        }

        // GET: Kalenders/Edit/5
        public ActionResult Edit(int? id)
        {

            

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Kalender kalender = db.Kalender.Find(id);

            if (kalender == null)
            {
                return HttpNotFound();
            }

            ViewBag.Key = new SelectList(db.KasutajaUus, "Id", "Eesnimi", kalender.Key);
            return View(kalender);
        }

        // POST: Kalenders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "nr,Key,Kuupäev,Tund,TunniHInd,Staatus")] Kalender kalender)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kalender).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction($"Details/{kalender.Key}", "KasutajaUus");
                //return RedirectToAction("Index");
            }

            //ViewBag.nr = kalender.nr;
            ViewBag.Key = new SelectList(db.KasutajaUus, "Id", "Eesnimi", kalender.Key);
            return View(kalender);
        }

        // GET: Kalenders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kalender kalender = db.Kalender.Find(id);
            if (kalender == null)
            {
                return HttpNotFound();
            }
            return View(kalender);
        }

        // POST: Kalenders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Kalender kalender = db.Kalender.Find(id);
            db.Kalender.Remove(kalender);
            db.SaveChanges();
            return RedirectToAction($"Details/{kalender.Key}", "KasutajaUus");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

L_Advisory/Views/Kalenders/BroneeringComplete.cshtml
@model Kalender

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    TÄNAN!

        @Html.ActionLink("Tagasi profiili juurde", "Index", "KasutajaUus")
    </div>
</body>
</html>

L_Advisory/Views/Kalenders/Create.cshtml
@model L_Advisory.Kalender

@{
    ViewBag.Title = "Lisa kalendrisse aeg";

    List<SelectListItem> staatus = new List<SelectListItem>()
            {
                new SelectListItem() { Text = "Vaba", Value = "1"},
                new SelectListItem() { Text = "Broneeritud", Value = "2"},
                new SelectListItem() { Text = "Hõivatud", Value = "3"},
            };

}
@if (KasutajaUus.ByEmail(User.Identity.Name).Id == Model.Key)
{
    <h2>Lisa kalendrisse uus sündmus</h2>
}
else
{
    <h2>Broneeri aeg!</h2>
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @*@Html.LabelFor(model => model.Key, "Key", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.HiddenFor(model => model.Key, new { htmlAttributes = new { @class = "form-control" }})
                @*@Html.EditorFor(model => model.Key, new { htmlAttributes = new { @class = "form-control", disabled = true } })*@
                @Html.ValidationMessageFor(model => model.Key, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kuupäev, htmlAttributes: new { @class = "control-label col-md-2"})
            (pp/kk/aaaa)
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kuupäev, new { htmlAttributes = new { @class = "form-control datepicker"} })
                @*@Html.ValidationMessageFor(model => model.Kuupäev, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Kellaaeg", htmlAttributes: new { @class = "control-label col-md-2" })
            (ühekordne arv)
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tund, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tund, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (KasutajaUus.ByEmail(User.Identity.Name).Id == Model.Key)
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Staatus, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Staatus, staatus, new { @class = "form-control" })
                    @*@Html.EditorFor(model => model.Staatus, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.Staatus, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Hind (€/tund)", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TunniHind, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TunniHind, "", new { @class = "text-danger" })
                </div>
            </div>
        }
        else
        {
            <div class="form-group">
                @*@Html.LabelFor(model => model.Staatus, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    <!-- niimoodi peab ette andma väärtuse, mida ma tahan edastada -->
                    @{Model.Staatus = 2;}
                    @Html.HiddenFor(model => model.Staatus, new { htmlAttributes = new { @class = "form-control"} })
                    @*@Html.ValidationMessageFor(model => model.Staatus, "", new { @class = "text-danger" })*@
                </div>
            </div>
        }


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @if (KasutajaUus.ByEmail(User.Identity.Name).Id == Model.Key)
                 {
                    <input type="submit" value="Lisa" class="btn btn-default" />
                 }
                 else
                 {
                    <input type="submit" value="Broneeri" class="btn btn-default" />
                 }
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tagasi profiili juurde", $"Details/{Model.Key}", "KasutajaUus")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

L_Advisory/Views/Kalenders/Delete.cshtml
@model L_Advisory.Kalender

@{
    ViewBag.Title = "Delete";
}

<h2>Kustuta kalendrist kirje</h2>

<h3>Oled sa kindel, et sa tahad seda teha?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Kuupäev)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kuupäev)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tund)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tund)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TunniHind)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TunniHind)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Ups, ma ei tahtnud tegelikult siia üldse tulla! Vii mind tagasi!", $"Details/{KasutajaUus.ByEmail(User.Identity.Name).Id}", "KasutajaUus")
        </div>
    }
</div>

L_Advisory/Views/Kalenders/Details.cshtml
@model L_Advisory.Kalender

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Kalender</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Kuupäev)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kuupäev)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tund)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tund)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TunniHind)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TunniHind)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KasutajaUus.Eesnimi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KasutajaUus.Eesnimi)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Key }) |
    @Html.ActionLink("Back to List", "Index")
</p>

L_Advisory/Views/Kalenders/Edit.cshtml
@model L_Advisory.Kalender

@{
    ViewBag.Title = "Muuda kalendrit";

    List<SelectListItem> staatus = new List<SelectListItem>()
            {
                new SelectListItem() { Text = "Vaba", Value = "1"},
                new SelectListItem() { Text = "Broneeritud", Value = "2"},
                new SelectListItem() { Text = "Hõivatud", Value = "3"},
            };

}

@if (KasutajaUus.ByEmail(User.Identity.Name).Id == Model.Key)
{
    <h2>Muuda kalendrisündmust</h2>
}
else
{
    <h2>Kinnita borneering @Model.Kuupäev.Date.ToShortDateString() kell @Model.Tund:00</h2>
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.nr)
        @Html.HiddenFor(model => model.Key)
        
        @if (KasutajaUus.ByEmail(User.Identity.Name).Id == Model.Key)
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Kuupäev, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Kuupäev, new { htmlAttributes = new { @class = "form-control", @Value = Model.Kuupäev.ToShortDateString().Replace(".", "/") } })
                    @Html.ValidationMessageFor(model => model.Kuupäev, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Tund, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Tund, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Tund, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TunniHind, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TunniHind, new { htmlAttributes = new { @class = "form-control", @Value = Model.TunniHind.ToString().Replace(",00", "") } })
                    @Html.ValidationMessageFor(model => model.TunniHind, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Staatus, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Staatus, staatus, new { @class = "form-control" })
                    @*@Html.EditorFor(model => model.Staatus, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.Staatus, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>

        }
        else
        {
            @Html.HiddenFor(model => model.Kuupäev)
            @Html.HiddenFor(model => model.Tund)
            @Html.HiddenFor(model => model.TunniHind)
            <p>
                @{Model.Staatus = 2;}
                @Html.HiddenFor(model => model.Staatus, new { @class = "form-control" })
            </p>

            <div class="form-group">
         
                    <input type="submit" value="Kinnita broneering" class="btn btn-default" />
         
            </div>
        }

        
    </div>
}

<div>
   @Html.ActionLink("Katkesta", $"Details/{Model.Key}", "KasutajaUus")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

L_Advisory/Views/Kalenders/Index.cshtml
@model IEnumerable<L_Advisory.Kalender>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Kuupäev)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tund)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TunniHind)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KasutajaUus.Eesnimi)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Kuupäev)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tund)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TunniHind)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.KasutajaUus.Eesnimi)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Key }) |
            @Html.ActionLink("Details", "Details", new { id=item.Key }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Key })
        </td>
    </tr>
}

</table>

L_Advisory/Views/Kalenders/Kalender.cshtml
@model IDictionary<DateTime, List<Kalender>>

<style>
    #kalender {
        table-layout: fixed;
        width: 100%;
        font-size: 12px;
    }
    td {
        border: 1px solid black;
        text-align: right;
        vertical-align: top;
    }
    th {
        text-align: center;
        border: 1px solid black;
    }
    #pealkirjad {
        text-align: left;
    }
    #sisemine {
        border: 0px;
        table-layout: fixed;
        width: 90px;
        height: 80px;
    }
    #seekuu {
        color: black;
    }
    #mitteseekuu {
        color: lightgray;
    }
    #vaba {
        background-color: lightgreen;
        font-size: 12px;
        line-height: 12px;
        margin: 0;
        padding: 0;
    }
    #broneeritud {
        background-color: yellow;
        font-size: 12px;
        line-height: 12px;
        margin: 0;
        padding: 0;
    }
    #kinni {
        background-color: red;
        font-size: 12px;
        line-height: 12px;
        margin: 0;
        padding: 0;
    }
    #kuunimi {
        padding: 20px;
        font-size: large;
    }
</style>
<div id="kuunimi">
    <b>@ViewBag.Täna.ToString("MMMM").ToUpper()</b>
</div>

@{
    // võtab antud sessioonist mudeli id
    var id = Session["Model.Id"];
    int id2 = (int)id;

    // ainult need mudeli väljad, mille key vastab id2-le
    var Model2 = Model.ToDictionary(x => x.Key, x => x.Value.Where(y => y.Key == id2));

}

<table id="kalender" width="500" height="500">
    <tr>
        <td style="text-align:left; border:none">

            @Html.ActionLink("< Eelmine", $"Kalender/{ViewBag.KalenderId - 30}")
            @*<a hfer='@Url.Action("Kalender", "Kalenders", new { id = (ViewBag.KalenderId - 30) })'>Proov</a>*@
        </td>
        @for (int i = 0; i < 5; i++)
         {
            <td style="border:none"></td>
         }
        <td style="text-align:right; border:none">
            @Html.ActionLink("Järgmine >", $"Kalender/{ViewBag.KalenderId + 30}")
        </td>
    </tr>

    <tr>
        <th style="color:red">Pühapäev</th>
        <th>Esmaspäev</th>
        <th>Teisipäev</th>
        <th>Kolmpäev</th>
        <th>Neljapäev</th>
        <th>Reede</th>
        <th style="color:red">Laupäev</th>
    </tr>

    @for (int i = 0; i < 5; i++)
    {
        <tr>
            @for (int j = 0; j < 7; j++)
            {
                DateTime d = ViewBag.AlgRida.AddDays(7 * i + j);
                <td style="@((j == 0 || j == 6) ? "color: red" : "color: black")">
                    @d.ToString("dd")
                    <table id="sisemine">
                        <tr style="border:none">
                            <td style="border:none">
                                <!-- if lause paneb asjad õigesse kohta -->
                                @if (Model.ContainsKey(ViewBag.AlgRida.AddDays(7 * i + j)))
                                {

                                    foreach (var item in Model2[ViewBag.AlgRida.AddDays(7 * i + j)])
                                    {
                                        if (KasutajaUus.ByEmail(User.Identity.Name).Id == id2)
                                        {
                                            if (item.Staatus == 1)
                                            {
                                                <p id="vaba">
                                                    @Html.ActionLink("x", "Delete", new { id = item.nr }, new { @style = "float:left" })
                                                    @Html.ActionLink($"{item.Tund}:00", "Edit", new { id = item.nr })
                                                </p>

                                            }
                                            else if (item.Staatus == 2)
                                            {
                                                <p id="broneeritud">
                                                    @Html.ActionLink("x", "Delete", new { id = item.nr }, new { @style = "float:left" })
                                                    @Html.ActionLink($"{item.Tund}:00", "Edit", new { id = item.nr })
                                                </p>
                                            }
                                            else
                                            {
                                                <p id="kinni">
                                                    @Html.ActionLink("x", "Delete", new { id = item.nr }, new { @style = "float:left" })
                                                    @Html.ActionLink($"{item.Tund}:00", "Edit", new { id = item.nr })
                                                </p>
                                            }
                                        }
                                        else
                                        {
                                            if (item.Staatus == 1)
                                            {
                                                <p id="vaba">
                                                    @Html.ActionLink($"{item.Tund}:00", "Edit", new { id = item.nr })
                                                    @*@(item.Tund + ":00")*@
                                                </p>

                                            }
                                            else if (item.Staatus == 2)
                                            {
                                                <p id="broneeritud">
                                                    @(item.Tund + ":00")
                                                </p>
                                            }
                                            else
                                            {
                                                <p id="kinni">
                                                    @(item.Tund + ":00")
                                                </p>
                                            }
                                        }
                                    }
                                }
                            </td>
                        </tr>
                    </table>
                </td>
            }
        </tr>
    }
</table>